### ISSUE TITLE
[BUG] Segmentation fault occurs when it destruct InputContext

### ISSUE THREAD

**Issue by onting** [Hanjp-IM/libhanjp#23]
Currently, we have an memory issue for preedit string in InputContext object.
I'm testing library code using below
```
#include "hanjpinputcontext.h"

int main()
{
    int i;
    HanjpInputContext *context;
    GArray *preedit;
    GArray *committed;
    GArray *hangul;
    gchar *res;

    const char *s = "gkwlapaktlxp.";

    context = hanjp_ic_new();
    preedit = hanjp_ic_ref_preedit_string(context);
    committed = hanjp_ic_ref_commit_string(context);
    hangul = hanjp_ic_ref_hangul_string(context);
    for(i = 0; s[i]; i++) {
        hanjp_ic_process(context, s[i]);
    }
    res = g_ucs4_to_utf8((const gunichar*)committed->data, committed->len, NULL, NULL, NULL);
    g_object_unref(context);
    return 0;
}
```
This code pushs string representing "하지메마시테." to InputContext.
I suggest you to write test program like above and link libhanjp for test, and run it on GDB.
For this, you should add program building code to CMakeLists.txt like below
```
...
add_exectutable(test_suit test.c)
target_link_libraries(test_suit hanjp)
...
```
VS Code UI is convenient for variable inspection.

This issue is related in preedit string manipulation code, so you should check ic_process, am_push, and ic_dispose.

**Comment by JSYoo5B** [comment]
I believe I found the reason for this segfault

```
(gdb) bt
#0  0x00007ffff7f8a6f0 in g_type_check_instance_is_fundamentally_a ()
    at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff7f67b99 in g_object_unref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x0000555555556a0c in hanjp_ic_dispose (self=0x55555556f870)
    at /home/jsyoo5b/Workspace/hanjp/libhanjp/hanjpinputcontext.c:38
#3  0x00007ffff7f67c93 in g_object_unref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x0000555555556638 in main () at /home/jsyoo5b/Workspace/hanjp/libhanjp/test.c:22
```

the codes around libhanjp/hanjpinputcontext.c:38 is following:
https://github.com/JSYoo5B/libhanjp/blob/17d5c6280e72393c77661f9f08ce4ce4e31a35b4/hanjpinputcontext.c#L37-L40

as you know, `priv->preedit` is GArray.
If you'd like to clear(unref) array, It must be cleared by GArray's interface. [`g_array_unref()`](https://docs.gtk.org/glib/type_func.Array.unref.html)

**Comment by onting** [comment]
Fixed by above PR
